apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: cart
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-microservices
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/instance: cart
    app.kubernetes.io/part-of: t2-microservices
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/instance: cart
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-microservices
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: cart
      app.kubernetes.io/part-of: t2-microservices
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app.kubernetes.io/name: cart
        app.kubernetes.io/instance: cart
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: "1.3"
        app.kubernetes.io/part-of: t2-microservices
    spec:
      containers:
        - name: cart
          imagePullPolicy: Always
          env:
            - name: MONGO_HOST
              value: mongo-cart-mongodb
            - name: T2_CART_TTL
              value: "0"
            - name: T2_CART_TASKRATE
              value: "0"
            - name: T2_JAEGER_ENABLED
              value: "FALSE"
            - name: T2_JAEGER_HOST
              value: simplest-agent #todo
          image: t2project/cart:main
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always
