apiVersion: v1
kind: Service
metadata:
  name: creditinstitute
  labels:
    app.kubernetes.io/name: creditinstitute
    app.kubernetes.io/instance: creditinstitute
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-microservices
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/instance: creditinstitute
    app.kubernetes.io/part-of: t2-microservices
  ports:
  - port: 80
    targetPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: creditinstitute-solomon
#   labels:
#     app.kubernetes.io/name: creditinstitute
#     app.kubernetes.io/component: backend
#     app.kubernetes.io/version: "1.3"
#     app.kubernetes.io/part-of: t2-microservices
#     monitoring: "true"
#     solomonTarget: "true"
#   # annotations:
#   #   prometheus.io/scrape: "true"
#   #   prometheus.io/path: /metrics
#   #   prometheus.io/port: "5000"
# spec:
#   selector:
#     app.kubernetes.io/instance: creditinstitute
#     app.kubernetes.io/part-of: t2-microservices
#   ports:
#     - protocol: TCP
#       name: http
#       port: 80
#       targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditinstitute
  labels:
    app.kubernetes.io/name: creditinstitute
    app.kubernetes.io/instance: creditinstitute
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-microservices
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: creditinstitute
      app.kubernetes.io/part-of: t2-microservices
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app.kubernetes.io/name: creditinstitute
        app.kubernetes.io/instance: creditinstitute
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: "1.3"
        app.kubernetes.io/part-of: t2-microservices
    spec:
      containers:
        - name: creditinstitute
          imagePullPolicy: Always
          env:
            - name: T2_JAEGER_ENABLED
              value: "FALSE"
            - name: T2_JAEGER_HOST
              value: simplest-agent #todo
          image: t2project/creditinstitute:main
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always
