apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  labels:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/instance: orchestrator
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-microservices
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/instance: orchestrator
    app.kubernetes.io/part-of: t2-microservices
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  labels:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/instance: orchestrator
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-microservices
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: orchestrator
      app.kubernetes.io/part-of: t2-microservices
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app.kubernetes.io/name: orchestrator
        app.kubernetes.io/instance: orchestrator
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: "1.3"
        app.kubernetes.io/part-of: t2-microservices
    spec:
      containers:
        - name: orchestrator
          imagePullPolicy: Always
          env:
            - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
              value: kafka-zookeeper:2181
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_PASSWORD
              value: eventuate
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-orchestrator/eventuate
            - name: SPRING_DATASOURCE_USERNAME
              value: eventuate
            - name: T2_JAEGER_ENABLED
              value: "FALSE"
            - name: T2_JAEGER_HOST
              value: simplest-agent #todo
          image: t2project/orchestrator:main
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always
