apiVersion: v1
kind: Service # headless
metadata:
  name: postgres-inventory
  labels:
    app.kubernetes.io/name: eventuate-tram-sagas-postgres
    app.kubernetes.io/instance: postgres-inventory
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 0.23.0.RELEASE
    app.kubernetes.io/part-of: t2-microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app.kubernetes.io/instance: postgres-inventory
    app.kubernetes.io/part-of: t2-microservices
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-inventory
  labels:
    app.kubernetes.io/name: eventuate-tram-sagas-postgres
    app.kubernetes.io/instance: postgres-inventory
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 0.23.0.RELEASE
    app.kubernetes.io/part-of: t2-microservices
spec:
  serviceName: postgres-inventory
  selector:
    matchLabels:
      app.kubernetes.io/instance: postgres-inventory
      app.kubernetes.io/part-of: t2-microservices
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eventuate-tram-sagas-postgres
        app.kubernetes.io/instance: postgres-inventory
        app.kubernetes.io/component: database
        app.kubernetes.io/version: 0.23.0.RELEASE
        app.kubernetes.io/part-of: t2-microservices
    spec:
      containers:
        - name: postgres
          image: eventuateio/eventuate-tram-sagas-postgres:0.23.0.RELEASE
          env:
            - name: POSTGRES_DB
              value: inventory
            - name: POSTGRES_PASSWORD
              value: inventory
            - name: POSTGRES_USER
              value: inventory
            - name: USE_DB_ID
              value: "true"
          args:
            - -c
            - max_connections=1000 # default: 100
            - -c
            - shared_buffers=256MB # default: 128MB
          ports:
            - containerPort: 5432
          volumeMounts:
          - name: datadir
            mountPath: /var/lib/postgresql/data
            subPath: postgres
          resources:
            # limits:
            #   cpu: 500m
            #   memory: 500Mi
            requests:
              cpu: 150m
              memory: 150Mi
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
