name: Build and push Docker image

on:
  workflow_dispatch:
  push:

jobs:

  build-and-push-docker-image:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: ./gradlew pushImage

  delete-untagged-docker-images:

    needs: build-and-push-docker-image

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Delete untagged Docker images
        uses: actions/delete-package-versions@v4
        with:
          package-name: clara-app
          package-type: container
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
